[options]
; Senha Master do Administrador para criação/backup de bancos de dados
admin_passwd = admin_capes_master_2026

; Caminhos dos Addons do Odoo
addons_path = /mnt/extra-addons,/mnt/external-addons,/usr/lib/python3/dist-packages/odoo/addons

; Conexão com o PostgreSQL
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_capes_secure_pass_2026
db_name = False

; Parametrizações de Performance e Limites
workers = 2
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Configurações de Log
log_level = info
logfile = False
log_handler = [':INFO']

; Configuração HTTP e Proxy
http_enable = True
proxy_mode = True
